image: fedora:29

stages:
  - build

before_script:
  - dnf update -y
  - >
    dnf install -y \
      gcc \
      rpm-devel \
      desktop-file-utils \
      docbook-utils \
      gettext \
      glib2-devel \
      gtk3-devel \
      itstool \
      libcanberra-devel \
      libgusb-devel \
      libudisks2-devel \
      libgudev1-devel \
      libappstream-glib \
      polkit-devel \
      meson \
      ninja-build

build-gnome-multi-writer:
  stage: build
  script:
  - meson _build .
  - ninja -v -C _build
  - meson test -v -C _build
